from typing import TypedDict, List, Optional, Any
from langchain_core.messages import BaseMessage


class AgentState(TypedDict, total=False):
    """
    Shared state for the LangGraph agent workflow.

    All agent nodes read from and write to this state.
    """

    # Conversation messages (user query, assistant responses)
    messages: List[BaseMessage]

    # Retrieved context from vector store
    context: List[dict[str, Any]]

    # Query plan generated by planner
    plan: Optional[str]

    # Critique/feedback from critic agent
    critique: Optional[str]

    # Groundedness score (0.0 to 1.0)
    score: Optional[float]

    # Final synthesized answer
    answer: Optional[str]

    # Raw input for ingestion
    raw_input: Optional[str]

    # Source identifier for ingestion
    source: Optional[str]

    # Number of chunks ingested
    chunks_ingested: Optional[int]

    # Error message if any
    error: Optional[str]
